name: Varo
version: '${project.version}'
main: dev.onetone.varo.Varo
api-version: 1.19
commands:
  reloadborder:
    description: This command reloads the world border size
    permission: op #varo.reloadborder
  testvictory:
    description: This command is used to test the victory animations and messages.
    permission: op #varo.testvictory
  setwinnerpodest:
    description: This command is used to set the winner's podest.
    permission: op #varo.setwinnerpodest
  jointeam:
    description: joins a team.
    permission: op
  getteam:
    description: gets a player's team
    permission: op


